### ISSUE TITLE
有的直播间无法生效

### ISSUE THREAD

**Issue by solo7917** [Executor-Cheng/BililiveNotification#4]
使用过程中遇到两个直播间无法生效，房间号是27484357、26995318，都是比较新的直播间，好像都是今年开的，可能和这有关？点击测试通知效果时报错如图
![image](https://github.com/Executor-Cheng/BililiveNotification/assets/139970150/eb7dedf1-a479-4b19-96cc-531b07deb667)

**Comment by Executor-Cheng** [comment]
感谢反馈, 晚上将会修复这个问题
