### ISSUE TITLE
无法正常收到开播/下播消息

### ISSUE THREAD

**Issue by Executor-Cheng** [Executor-Cheng/BililiveNotification#6]
哔哩哔哩直播最近又更改了匿名弹幕服务器连接的推送策略
如果握手包中的uid=0, 将导致弹幕服务器侧drop掉绝大多数消息的推送
考虑握手的时候置uid为要连接的直播间主播用户Id以规避此问题

**Comment by solo7917** [comment]
期待更新修复，现在已经完全不提醒了
